# Generated by Django 3.1.6 on 2023-10-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='challenger',
            field=models.TextField(blank=False, max_length=64),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender',
            field=models.CharField(blank=False, max_length=64),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.CharField(blank=False, max_length=64),
        ),
    ]
